name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Welcome to GitHub Actions
            run: echo "Welcome to GitHub Actions"
          - name: list the files
            run: ls



