name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.4
        
          - name: List and read file
            run: |
                echo "Welcome to GitHub Actions"
                ls -ltra
                cat README.md
          - name: Generate ASCII Artwork
            run: cowsay -f dragon "Run for cover ... RAWAAR" >> dragon.txt 

          #- name: list the files
          #  run: ls



