name: Generate ASCII Art work
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: get the list of files in directory 
            run: ls -ltr
          - name: Execute shell script
            run:  |
                chmod +x ascii-create.sh
                ./ascii-create.sh
          

