name: Multiple Generate ASCII Art work
on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: get the list of files in directory 
            run: ls -ltr
          - name: Install cowsay 
            run: sudo apt-get install cowsay -y
          - name: Execute cowsay script
            run:  cowsay -f dragon "Run for cover I am a DRAGON... RAWAAR" >> dragon.txt
        
    test_job:
        needs:   build_job
        runs-on: ubuntu-latest
        steps:
          - name: find text in file
            run: grep -i "dragon" dragon.txt
    deploy_job:
        needs:   [build_job,test_job]
        runs-on: ubuntu-latest
        steps:
           - name: list of files in directory
             run: cat dragon.txt
                      
          

